"""Add preferences and login_count to User model

Revision ID: add_user_prefs
Revises: 8decc4302f89
Create Date: 2024-12-07 18:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_user_prefs'
down_revision = '8decc4302f89'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferences', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('login_count', sa.Integer(), nullable=True))
    
    # Set default values for existing users
    op.execute("UPDATE users SET preferences = '{}' WHERE preferences IS NULL")
    op.execute("UPDATE users SET login_count = 0 WHERE login_count IS NULL")
    
    # Make columns non-nullable after setting defaults
    op.alter_column('users', 'preferences', nullable=False)
    op.alter_column('users', 'login_count', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'login_count')
    op.drop_column('users', 'preferences')
    # ### end Alembic commands ###